create table
  public."Activity" (
    id text not null,
    "userId" text null,
    title text null,
    "_createdAt" timestamp with time zone not null default now(),
    _deleted boolean null,
    type text null,
    description text null,
    "markerFileId" text null,
    "markerImagesIds" jsonb null,
    "markerImagesCfg" jsonb null,
    "markerImages" jsonb null,
    "markerFile" text null,
    "_updatedAt" timestamp with time zone null,
    instruction text null,
    "comboIds" jsonb null,
    token text null,
    auth text null,
    constraint Activity_pkey primary key (id)
  ) tablespace pg_default;

  create table
  public."Aura" (
    id text not null,
    "_createdAt" timestamp with time zone not null default now(),
    "activityId" text null,
    _deleted boolean null,
    type text null,
    cfg jsonb null,
    meta jsonb null,
    content jsonb null,
    "userId" text null,
    "_updatedAt" timestamp with time zone null,
    constraint Aura_pkey primary key (id)
  ) tablespace pg_default;

  create table
  public."Authorization" (
    id bigint generated by default as identity,
    auth text not null,
    title text null,
    token text null,
    "userId" text null,
    created_at timestamp with time zone null,
    constraint Authorization_pkey primary key (id)
  ) tablespace pg_default;

  create table
  public."Trace" (
    id bigint generated by default as identity,
    "_createdAt" timestamp with time zone not null default now(),
    "userId" text null,
    "activityId" text null,
    "auraId" text null,
    "traceType" text null,
    timestamp bigint null,
    "timestampIso" text null,
    duration double precision null,
    "activityType" text null,
    constraint Trace_pkey primary key (id)
  ) tablespace pg_default;