export enum TRACES {
  ADD_ACTIVITY_CTA = 'ADD_ACTIVITY_CTA',
  SELECT_ACTIVITY_TYPE = 'SELECT_ACTIVITY_TYPE',

  ENTER_NAMING_STEP = 'ENTER_NAMING_STEP',
  EXIT_NAMING_STEP = 'EXIT_NAMING_STEP',

  ENTER_MARKER_STEP = 'ENTER_MARKER_STEP',
  EXIT_MARKER_STEP = 'EXIT_MARKER_STEP',

  ENTER_AURA_STEP = 'ENTER_AURA_STEP',
  EXIT_AURA_STEP = 'EXIT_AURA_STEP',

  ENTER_TRY_STEP = 'ENTER_TRY_STEP',
  EXIT_TRY_STEP = 'EXIT_TRY_STEP',

  ENTER_SUCCESS_STEP = 'ENTER_SUCCESS_STEP',
  EXIT_SUCCESS_STEP = 'EXIT_SUCCESS_STEP',

  ENTER_FAILURE_STEP = 'ENTER_FAILURE_STEP',
  EXIT_FAILURE_STEP = 'EXIT_FAILURE_STEP',

  ENTER_SELECT_STEP = 'ENTER_SELECT_STEP',
  EXIT_SELECT_STEP = 'EXIT_SELECT_STEP',

  ENTER_ARRANGE_STEP = 'ENTER_ARRANGE_STEP',
  EXIT_ARRANGE_STEP = 'EXIT_ARRANGE_STEP',

  REMOVE_ACTIVITY = 'REMOVE_ACTIVITY',

  ADD_AURA = 'ADD_AURA',
  REMOVE_AURA = 'REMOVE_AURA',
  DRAG_AURA = 'DRAG_AURA',
  RESIZE_AURA = 'RESIZE_AURA',
  ROTATE_AURA = 'ROTATE_AURA',
  UPDATE_AURA = 'UPDATE_AURA',
  STYLE_AURA = 'STYLE_AURA',

  ENTER_CROP_MARKER = 'ENTER_CROP_MARKER',
  EXIT_CROP_MARKER = 'EXIT_CROP_MARKER',
  ADD_MARKER = 'ADD_MARKER',
  REMOVE_MARKER = 'REMOVE_MARKER',
}
